// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.RateCalculator.Client.AutorestClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AssetPair
    {
        /// <summary>
        /// Initializes a new instance of the AssetPair class.
        /// </summary>
        public AssetPair()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AssetPair class.
        /// </summary>
        public AssetPair(string id, string baseAssetId, string quotingAssetId, int accuracy, int invertedAccuracy, bool isDisabled, string name, double minVolume, double minInvertedVolume, string source, string source2, string exchangeId)
        {
            Id = id;
            BaseAssetId = baseAssetId;
            QuotingAssetId = quotingAssetId;
            Accuracy = accuracy;
            InvertedAccuracy = invertedAccuracy;
            IsDisabled = isDisabled;
            Name = name;
            MinVolume = minVolume;
            MinInvertedVolume = minInvertedVolume;
            Source = source;
            Source2 = source2;
            ExchangeId = exchangeId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BaseAssetId")]
        public string BaseAssetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "QuotingAssetId")]
        public string QuotingAssetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Accuracy")]
        public int Accuracy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "InvertedAccuracy")]
        public int InvertedAccuracy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsDisabled")]
        public bool IsDisabled { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MinVolume")]
        public double MinVolume { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MinInvertedVolume")]
        public double MinInvertedVolume { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Source")]
        public string Source { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Source2")]
        public string Source2 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ExchangeId")]
        public string ExchangeId { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Id == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Id");
            }
            if (BaseAssetId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "BaseAssetId");
            }
            if (QuotingAssetId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "QuotingAssetId");
            }
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
            if (Source == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Source");
            }
            if (Source2 == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Source2");
            }
            if (ExchangeId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ExchangeId");
            }
        }
    }
}
