// Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.RateCalculator.Client.AutorestClient.Models
{
    using Lykke.Service;
    using Lykke.Service.RateCalculator;
    using Lykke.Service.RateCalculator.Client;
    using Lykke.Service.RateCalculator.Client.AutorestClient;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class BalanceRecordWithBase
    {
        /// <summary>
        /// Initializes a new instance of the BalanceRecordWithBase class.
        /// </summary>
        public BalanceRecordWithBase()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BalanceRecordWithBase class.
        /// </summary>
        public BalanceRecordWithBase(string assetId = default(string), double? balance = default(double?), string baseAssetId = default(string), double? amountInBase = default(double?))
        {
            AssetId = assetId;
            Balance = balance;
            BaseAssetId = baseAssetId;
            AmountInBase = amountInBase;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetId")]
        public string AssetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Balance")]
        public double? Balance { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BaseAssetId")]
        public string BaseAssetId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AmountInBase")]
        public double? AmountInBase { get; set; }

    }
}
