// Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.RateCalculator.Client.AutorestClient.Models
{
    using Lykke.Service;
    using Lykke.Service.RateCalculator;
    using Lykke.Service.RateCalculator.Client;
    using Lykke.Service.RateCalculator.Client.AutorestClient;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class IFeedData
    {
        /// <summary>
        /// Initializes a new instance of the IFeedData class.
        /// </summary>
        public IFeedData()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the IFeedData class.
        /// </summary>
        public IFeedData(string asset = default(string), System.DateTime? dateTime = default(System.DateTime?), double? bid = default(double?), double? ask = default(double?))
        {
            Asset = asset;
            DateTime = dateTime;
            Bid = bid;
            Ask = ask;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Asset")]
        public string Asset { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateTime")]
        public System.DateTime? DateTime { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Bid")]
        public double? Bid { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Ask")]
        public double? Ask { get; private set; }

    }
}
