// Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.RateCalculator.Client.AutorestClient.Models
{
    using Lykke.Service;
    using Lykke.Service.RateCalculator;
    using Lykke.Service.RateCalculator.Client;
    using Lykke.Service.RateCalculator.Client.AutorestClient;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for OperationResult.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OperationResult
    {
        [EnumMember(Value = "Unknown")]
        Unknown,
        [EnumMember(Value = "Ok")]
        Ok,
        [EnumMember(Value = "InvalidInputParameters")]
        InvalidInputParameters,
        [EnumMember(Value = "NoLiquidity")]
        NoLiquidity
    }
}
