// Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.RateCalculator.Client.AutorestClient.Models
{
    using Lykke.Service;
    using Lykke.Service.RateCalculator;
    using Lykke.Service.RateCalculator.Client;
    using Lykke.Service.RateCalculator.Client.AutorestClient;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TupleStringDouble
    {
        /// <summary>
        /// Initializes a new instance of the TupleStringDouble class.
        /// </summary>
        public TupleStringDouble()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TupleStringDouble class.
        /// </summary>
        public TupleStringDouble(string item1 = default(string), double? item2 = default(double?))
        {
            Item1 = item1;
            Item2 = item2;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Item1")]
        public string Item1 { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Item2")]
        public double? Item2 { get; private set; }

    }
}
